name: DivineFakePlayer
main: com.divinefakeplayer.DivineFakePlayer
version: 1.0.0
api-version: '1.20'
depend: [Vault]
softdepend: [ProtocolLib]
commands:
  dfp:
    description: Reload DivineFakePlayer configuration.
    usage: /<command> reload
    permission: divinefakeplayer.reload
permissions:
  divinefakeplayer.reload:
    description: Allows reloading the DivineFakePlayer configuration.
    default: op
